### PR TITLE
improve latex install

### PR DESCRIPTION
**Pull request by pierre-24**
Based on some tests I did in Debian 9, and also https://github.com/zestedesavoir/latex-template/pull/87 !

### CODE REVIEW

**Comment by artragis** [comment]
@pierre-24 the build failed.

**Comment by pierre-24** [comment]
Indeed!

I'm not sure how it is related to my change, though, so if someone has an explanation, I would be happy :-°

**Comment by pierre-24** [comment]
Notice that there is now [a clear list of the differents latex packages](https://github.com/zestedesavoir/latex-template/blob/master/scripts/packages) that you can use. Also, our [texlive.profile](https://github.com/zestedesavoir/latex-template/blob/master/scripts/texlive.profile) is quite OK (I used it [here](https://github.com/zestedesavoir/zds-site/blob/dev/scripts/install_zds.sh#L181-L211)).

**Comment by Situphen** [comment]
@pierre-24 Is this pull request still needed? If so, could you rebase your branch? :)

**Comment by Situphen** [comment]
Up @pierre-24 !

**Comment by pierre-24** [comment]
I guess it is not needed anymore, since everything is ... Working ? ^^

**Comment by pierre-24** [comment]
(also, pourquoi qu'on parle anglais alors que la doc est en français sur ce dépot ? :p )

**Pull request closed without merging**
